ALTER TABLE patient MODIFY health_id VARCHAR(50) NOT NULL UNIQUE;

ALTER TABLE doctor MODIFY health_id VARCHAR(50) NOT NULL UNIQUE;

ALTER TABLE staff MODIFY health_id VARCHAR(50) NOT NULL UNIQUE;




